apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: podinfo
    patch: |
      - op: add
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 200m
          memory: 128Mi
